### ISSUE TITLE
Can not build locally

### ISSUE THREAD

**Issue by AsceticBear** [darwinia-network/darwinia-docs#3]
I tried following the instructions in README, but the result is unexpected.

```sh
1. yarn
2. yarn start
```

![image](https://user-images.githubusercontent.com/11801722/167594885-ed78f625-67eb-49df-8008-4d692b18f04f.png)

**Comment by wuminzhe** [comment]
click the turorial link

**Comment by wuminzhe** [comment]
change home to first doc now
